name: Terraform CI/CD

on:
  push:
    branches:
      - main   # Ya aapki desired branch (e.g., dev, staging)
  workflow_dispatch:  # Manual trigger option

jobs:
  terraform:
    name: Terraform Init, Plan, Apply
    runs-on: self-hosted  # Important: Runs on self-hosted runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0  # Use your preferred version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve


              
